---
- name: Gather System Information on Windows 10
  hosts: win
  tasks:
    - name: Gather OS Information
      win_shell: |
        Get-ComputerInfo | Select-Object CsName, WindowsVersion, OsArchitecture, OsBuildNumber, InstallDate
      register: os_info

    - name: Output OS Information
      debug:
        var: os_info.stdout_lines

    - name: Gather CPU Information
      win_shell: |
        Get-CimInstance -ClassName Win32_Processor | Select-Object Name, NumberOfCores, NumberOfLogicalProcessors
      register: cpu_info

    - name: Output CPU Information
      debug:
        var: cpu_info.stdout_lines

